[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'
evm_version = 'shanghai'
optimizer = true
optimizer-runs = 99_999
via_ir = true
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
